In [1]:
import numpy as np


# 1.Numpy

행렬이나 일반적으로 대규모 다차원 배열을 쉽게 처리할 수 있도록 지원하는 파이썬의 라이브러리

references: 
- [numpy](https://numpy.org/doc/stable/reference/index.html#reference)
- [cs231 numpy](https://cs231n.github.io/python-numpy-tutorial/)
- [Python For Data Science Cheat Sheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)

<br>

numpy 특징 <br>
- 파이썬 리스트에 비해 빠르고, 메모리 효율적
- 반복문 없이 배열에 대한 처리 지원
- 다양한 기능 제공
<br>
<br>

numpy 기능 <br>
- 1. shape: numpy dimension
- 2. ndim: shape에서 얼마나 나오는지
- 3. dtype: numpy 원소의 데이터 타입

## 1.1 배열 생성

### 1.1.1 기본 배열 생성

파이썬 배열 --> numpy array 

In [11]:
a = list(range(10))
np.array(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np.array([[[1,2,3],[4,5,6]],[[7,8,9],[7,8,9]]],dtype = np.float32).shape

(2, 2, 3)

In [13]:
list([[1,2,3],[4,5,6],[7,8,9]])

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

#### arange
일정 범위의 배열을 생성 <br>
python의 range와 유사 <br>
단, arange는 실수 사용 가능 <br>

> 주의 <br>
np.arange(-3, 3, 0.5, dtype=int) <br>
array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

<br>

사용법
```python
x = np.arange(0, 10)
x = np.arange(-5, 5, 0.5)
```

In [27]:
b= list(range(1,10))
zip(b)

In [19]:
a = np.arange(-3,3,0.5)

In [24]:
(a//2)**2


array([4., 4., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1.])

In [18]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

#### linspace

arange와 유사 <br>
start와 stop를 주어진 숫자 만큼 분할

<br>

사용법
```python
x = np.linspace(2, 3, num=5)
x = np.linspace(2, 3, num=5, endpoint=False)    # 끝 점 미포함 
```

In [3]:
r = [ i for i in range(1,101)]
((np.array(r)-1)//20) + 1 


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5], dtype=int32)

In [7]:
rank = np.random.choice(np.arange(1,101),size =100)
grade = ((rank-1)//20)+1

In [8]:
rank

array([100,  16,  85,  34,  74,  44,   4,   2,  60,  65,  77,  96,  29,
        92,  29,  47,  74,  73,   8,  15,  53,  78,  88,  13,  43,  12,
        13,  87,  74,  78,   9,  52,  14,  40,  73,  25,  12,  48,  45,
         9,  78,  67,  22,  40,   3,  39,  11,  24,  22,  82,  45,  14,
        85,   9,  95,  19,  82,  29,  30,  38,  61,  66,  77,  47,  32,
        97,  20,  80,  98,  27,  34,  65,  84,  49,  93,  15,  11,   3,
        98,  84,  80,  92,  19,  55,  88,  14,  36,  40,  17,  69,  16,
        34,   5,  37,  81,  70,  87,  86,  51,  22])

In [9]:
grade

array([5, 1, 5, 2, 4, 3, 1, 1, 3, 4, 4, 5, 2, 5, 2, 3, 4, 4, 1, 1, 3, 4,
       5, 1, 3, 1, 1, 5, 4, 4, 1, 3, 1, 2, 4, 2, 1, 3, 3, 1, 4, 4, 2, 2,
       1, 2, 1, 2, 2, 5, 3, 1, 5, 1, 5, 1, 5, 2, 2, 2, 4, 4, 4, 3, 2, 5,
       1, 4, 5, 2, 2, 4, 5, 3, 5, 1, 1, 1, 5, 5, 4, 5, 1, 3, 5, 1, 2, 2,
       1, 4, 1, 2, 1, 2, 5, 4, 5, 5, 3, 2], dtype=int32)

In [23]:
print(np.linspace(2,3,num=5))
print(np.linspace(2,3,num=5, endpoint = False))

[2.   2.25 2.5  2.75 3.  ]
[2.  2.2 2.4 2.6 2.8]


#### eye

대각행렬이 1이고 나머지가 0인 행렬 생성 <br>
k를 이용하여 1의 위치를 조정할 수 있음 <br>
<br>

사용법
```python
x = np.eye(10)    # np.identity와 동일
x = np.eye(10, k =1)
```

In [24]:
np.eye(5).

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### zeros

shape을 입력하면 모든 값이 0인 해당 shape에 맞는 배열 생성 <br>

사용법
```python
x = np.zeros(5)
x = np.zeros((5, 2), dtype=float)
```

#### ones

shape을 입력하면 모든 값이 1인 해당 shape에 맞는 배열 생성 <br>
<br>

사용법
```python
x = np.ones(5)
x = np.ones((5, 2), dtype=float)
```

#### full

shape과 숫자를 입력하면 입력한 숫자로 찬 해당 shape에 맞는 배열 생성 <br>
<br>

사용법
```python
x = np.full(5, np.inf)
x = np.full((5, 2), np.nan)
```

#### tril

lower triangle matrix 생성 <br>
m값을 이용하여 삼각행렬 이동 가능 <br>
<br>

사용법
```python
x = np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
x = np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)
```

#### triu

upper triangle matrix 생성 <br>
m값을 이용하여 삼각행렬 이동 가능 <br>
<br>

사용법
```python
x = np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
x = np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 1)
```

### 1.1.2 랜덤 배열 생성

#### random

균등분포에서 입력한 차원 만큼 데이터 생성 <br>
<br>

사용법
```python
x = np.random.random(size=(2, 3))    # size: dim
```

#### randint

지정한 범위 내에서 임의의 수 생성

사용법
```python
x = np.random.randint(0, 10, size=(5,2))    # size: dim
```

#### normal

정규분포에서 입력한 차원 만큼 데이터 생성 <br>
<br>

사용법
```python
x = np.random.normal(loc=0, scale=1, size=(2, 3))
# loc: 평균
# scale: 분산
# size: dim
```

#### randn

표준정규분포에서 입력한 차원 만큼 데이터 생성 <br>
<br>

사용법
```python
x = np.random.randn(2, 3)
```

## 1.2 배열 조작

### 1.2.1 배열 결합

#### concatenate

두 배열을 결합 <br>
<br>

사용법 
```python
a = np.arange(12).reshape(2, 6)
b = np.arange(12).reshape(2, 6)
np.concatenate([a, b], axis=0)
np.concatenate([a, b], axis=1)
```

### 1.2.2 배열 분할

#### array_split

주어진 배열을 분할 <br>
<br>

사용법
```python
x = np.arange(9.0)
np.split(x, 3)
np.split(x, [3, 5, 6, 10])
```

### 1.2.3 차원 변경

#### reshape

배열의 모양을 원하는 형태로 바꿈 <br>
단, 바꾸는 배열의 차원 곱은 원 배열의 차원 곱과 일치해야 함 <br>
<br>

사용법
```python
x = np.arange(30)
x.reshape(5, 6)
```


#### flatten

배열을 1차원 배열로 바꿈 <br>
<br>
사용법 <br>
```python
x = np.arange(30).reshape(2, 5, 3)
x.flatten()
```

#### squeeze

불필요한 차원을 제거 <br>
즉, 길이가 0인 차원을 제거 <br>
<br>

사용법
```python
x = np.arange(10).reshape(10, 1, 1)
x.squeeze()
```

#### expand_dims

차원 추가 <br>
<br>

사용법
```python
x = np.arange(10)
np.expand_dims(x, 0)
```

### 1.2.4 모양 변경

##### roll

배열을 입력한 수 만큼 이동 <br>
<br>

사용법
```python
x = np.arange(10)
np.roll(x, 2)
```

```python
x = np.reshape(x, (2, 5))
np.roll(x, 1)
np.roll(x, -1, axis=0)
np.roll(x, -1, axis=1)
```

##### flip

지정된 축을 기준으로 배열을 뒤집음 <br>
<br>

사용법

```python
x = np.arange(10).reshape(5, 2)
np.flip(x, 0)
```


### 1.2.5 축 변경

#### swapaxes

두 축의 위치를 지정하여 변경 <br>
<br>

사용법
```python
x = np.arange(100).reshape(5, 2, 10)
x.swapaxis(0, 2)    # 0 <-> 2
```

#### transpose

여러 축의 위치를 변경 <br>
transpose에 들어가는 인자는 축의 순서 <br>
<br>

사용법

```python
x = np.arange(100).reshape(5, 2, 10)
x.transpose(0, 2, 1)    # 1번 축과 2번 축을 바꿈
x.transpose(2, 0, 1)    # 2->0, 0->1, 1->2
```

### 1.2.6 배열 정렬

#### sort

주어진 축을 기준으로 배열 정렬 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, (5, 2))
x.sort(axis=1)
x
```



#### argsort

주어진 축을 기준으로 정렬된 배열의 인덱스 반환 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, (5, 2))
x.argsort(axis=1)
```


### 1.2.7 기타

##### unique

배열 내의 중복값 제거 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, (5, 2))
np.unique(x, axis=0)
```

#### nan_to_num

배열 내의 nan 값을 특정 숫자로 변환 <br>
<br>

사용법
```python
x = np.full((3, 4), np.nan)
np.nan_to_num(x, nan=1)


#### trim_zeros

배열 내의 0값을 제거 <br>
<br>

사용법
```python
x = np.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0))
np.trip_zeros(x, trip='f')    # 앞의 0만 제거
np.trip_zeros(x, trip='b')    # 뒤의 0만 제거
np.trip_zeros(x, trip='fb')   # 앞뒤 0 제거
```

stride_tricks

배열을 주어진 윈도우 만큼 분할 <br>
<br>

사용법
```python
x = np.arange(10)
y = np.lib.stride_tricks.sliding_window_view(x, 3)
```

## 1.3 배열 탐색

### argmax

축을 기준으로 배열에서 최댓걊의 index 반환 <br>
<br>

사용법
```python
x = np.arange(6).reshape(2,3)
np.argmax(x)
np.argmax(x, axis=0)
```

### argmin

축을 기준으로 배열에서 최솟걊의 index 반환 <br>
<br>

사용법
```python
x = np.arange(6).reshape(2,3)
np.argmin(x)
np.argmin(x, axis=0)
```



### where

특정 조건에 맞는 값의 index 반환 또는 값 변환 <br>
<br>

사용법
```python
x = np.arange(6).reshape(2,3)
np.where(x < 5)    # 조건을 만족하는 값의 인덱스 반환
np.where(x < 5, 1, 0)    # x가 5보다 작은 값은 1, 그렇지 않으면 0
```

### extract

특정 조건에 맞는 값을 반환 <br>
<br>

사용법
```python
x = np.arange(6).reshape(2,3)
np.extract(x > 2, x)
```

##  1.4 배열 연산

### matmul

행렬 곱 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, size=(2,2))
y = np.random.randint(0, 10, size=(2,2))

np.matmul(x, y)
x @ y
```

### eigen

eigenvalue, eigenvector 반환 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, size=(2,2))
np.linalg.eig(x)
```



### det

배열의 행렬식을 구함 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, size=(2,2))
np.linalg.det(x)
```

### trace
대각원소의 합 반환 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, size=(2,2))
np.trace(x)
```

### solve

선형 방정식의 해를 반환 <br>
<br>


사용법
```python
#  x_0 + 2*x_1 = 1
# 3x_0 + 5*x_1 = 2:
a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])
np.linalg.solve(a, b)
```

inv

선형 방정식의 해를 반환 <br>
<br>


사용법
```python
x = np.random.randint(0, 10, size=(2,2))
np.linalg.inv(x)
```

## 1.5 통계 함수

#### ptp

축별 최댓값 - 최솟값 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
x.ptp(axis=0)
```

#### median

축별 중앙값 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
np.median(x, axis=0)
```

### sum

축별 합 산출 <br>
<br>

사용법
```python
x = np.array([3, 4, 5])
x.sum(axis=1)
```

### average

축별 가중합 산출 <br>
<br>

사용법
```python
x = np.array([3, 4, 5])
np.average(x, weights=[0.5, 0.3, 0.2])
```

### mean

축별 평균 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
x.mean(axis=1)
```

### min

축별 최솟값 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
x.min(axis=1)
```

### min

축별 최댓값 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
x.max(axis=1)
```

### std
축별 표준편차 산출 <br>
<br>

사용법

```python
x = np.arange(12).reshape(4,3)
x.std(axis=1)
```

### cov

공분산 산출 <br>
<br>

사용법
```python
x = np.random.rand(25).reshape(5, 5)
np.cov(x)
```